### ISSUE TITLE
rename only works if src and dst are on the same device

### ISSUE THREAD

**Issue by lievenm** [fpco/haskell-filesystem#9]
In unix, rename uses the rename(2) system call which returns EXDEV when the src and dst aren't on the same device. Is this limitation intentional? This came up in the Turtle library (https://github.com/Gabriel439/Haskell-Turtle-Library/issues/37).

**Comment by snoyberg** [comment]
There's a good argument for the current behavior being the correct one, since we can't provide the same atomic behavior if the files are on different devices. I could imagine providing a wrapper function that first tries the rename system call, and if that fails does it the copy/delete way, but would want to call that out explicitly in the docs. Would that address your case?

**Comment by lievenm** [comment]
I think you've got a point that the current behaviour is reasonable. Additionally, people might expect a rename operation to be fast which it won't be if a copy is involved.
